# Configure the build for minimal size
[profile.dev]
panic = "abort"
lto = true
opt-level = 1

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[workspace]
members = [
    "macros",
    "sdfat32-rs",
    "examples",
]
